#!/bin/bash
echo "[*] Setting up Q104 (Mock) — CIS Benchmark"
echo ""
echo "Task: Run kube-bench and remediate the following findings:"
echo ""
echo "  Control-plane:"
echo "    - 1.2.17: Ensure --profiling=false (kube-apiserver)"
echo "    - 1.2.19: Ensure --audit-log-path is set (kube-apiserver)"
echo "    - 1.3.2:  Ensure --profiling=false (controller-manager)"
echo "    - 1.4.1:  Ensure --profiling=false (scheduler)"
echo ""
echo "  Worker node:"
echo "    - 4.2.6:  Ensure protectKernelDefaults is true (kubelet)"
echo ""
echo "Steps:"
echo "  1. Run kube-bench: kube-bench run -s master"
echo "  2. Fix each finding in the static pod manifests:"
echo "     /etc/kubernetes/manifests/kube-apiserver.yaml"
echo "     /etc/kubernetes/manifests/kube-controller-manager.yaml"
echo "     /etc/kubernetes/manifests/kube-scheduler.yaml"
echo "  3. For kubelet: edit /var/lib/kubelet/config.yaml"
echo ""
echo "Weight: 3%"
