#!/bin/bash
echo "[*] Setting up Q113 (Mock) — ImagePolicyWebhook"
echo ""
echo "Task:"
echo "  Configure an ImagePolicyWebhook to reject pod creation with"
echo "  unverified or unsigned images."
echo ""
echo "Steps:"
echo "  1. Create webhook admission config at /etc/kubernetes/admission/config.yaml:"
echo "     apiVersion: apiserver.config.k8s.io/v1"
echo "     kind: AdmissionConfiguration"
echo "     plugins:"
echo "     - name: ImagePolicyWebhook"
echo "       configuration:"
echo "         imagePolicy:"
echo "           kubeConfigFile: /etc/kubernetes/admission/kubeconfig.yaml"
echo "           allowTTL: 50"
echo "           denyTTL: 50"
echo "           retryBackoff: 500"
echo "           defaultAllow: false"
echo ""
echo "  2. Create kubeconfig at /etc/kubernetes/admission/kubeconfig.yaml:"
echo "     clusters:"
echo "     - cluster:"
echo "         server: https://image-webhook.default.svc:8443/validate"
echo "         certificate-authority: /etc/kubernetes/admission/ca.crt"
echo ""
echo "  3. Add to kube-apiserver manifest:"
echo "     --enable-admission-plugins=NodeRestriction,ImagePolicyWebhook"
echo "     --admission-control-config-file=/etc/kubernetes/admission/config.yaml"
echo ""
echo "  4. Verify: kubectl run test --image=unsigned-image:latest should be denied"
echo ""
echo "Weight: 6%"
