#!/bin/bash
echo "[*] Setting up Q15 — TLS Cipher Configuration"
echo ""
echo "Task:"
echo "  Configure specific TLS ciphers for kube-apiserver and etcd."
echo ""
echo "  1. kube-apiserver (/etc/kubernetes/manifests/kube-apiserver.yaml):"
echo "     Add: --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
echo ""
echo "  2. etcd (/etc/kubernetes/manifests/etcd.yaml):"
echo "     Add: --cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
echo ""
echo "  3. Wait for both to restart and verify:"
echo "     kubectl get pods -n kube-system"
echo ""
echo "Note: This requires direct node access to modify static pod manifests"
echo "      Changes will cause apiserver/etcd to restart"
