#!/bin/bash
echo "[*] Setting up Q106 (Mock) — TLS Cipher Configuration"
echo ""
echo "Task:"
echo "  Configure TLS ciphers for kube-apiserver and etcd to only allow strong ciphers."
echo ""
echo "  1. kube-apiserver (/etc/kubernetes/manifests/kube-apiserver.yaml):"
echo "     --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256"
echo ""
echo "  2. etcd (/etc/kubernetes/manifests/etcd.yaml):"
echo "     --cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
echo ""
echo "  3. Wait for both to restart:"
echo "     watch crictl ps"
echo "     kubectl get pods -n kube-system"
echo ""
echo "Note: Requires node access"
echo "Weight: 6%"
