#!/bin/bash
echo "[*] Setting up Q21 — Docker Security Configuration"
echo ""
echo "Task:"
echo "  Fix Docker daemon security on the worker node."
echo ""
echo "Steps:"
echo "  1. Remove user 'deployer' from the docker group:"
echo "     gpasswd -d deployer docker"
echo ""
echo "  2. Fix Docker socket permissions:"
echo "     chmod 660 /var/run/docker.sock"
echo "     chown root:docker /var/run/docker.sock"
echo ""
echo "  3. Verify no unauthorized users can access Docker:"
echo "     id deployer  (should not show 'docker' group)"
echo "     ls -la /var/run/docker.sock  (should be 660)"
echo ""
echo "Note: Requires SSH to worker node"
echo "      ssh node01"
