#!/bin/bash
echo "[*] Setting up Q05 — CIS Benchmark"
echo ""
echo "Task: Run kube-bench and fix the following:"
echo "  Control-plane:"
echo "    - 1.2.17: --profiling=false (kube-apiserver)"
echo "    - 1.3.2:  --profiling=false (controller-manager)"
echo "    - 1.4.1:  --profiling=false (scheduler)"
echo "  Worker node:"
echo "    - 4.2.6:  protectKernelDefaults: true (kubelet)"
echo ""
echo "Tools: kube-bench is pre-installed"
echo "Run: kube-bench run -s master"
echo "Run: kube-bench run -s node"
