#!/bin/bash
echo "[*] Setting up Q17 — Image Policy Webhook"
echo ""
echo "Task:"
echo "  Configure an ImagePolicyWebhook admission controller that denies"
echo "  images with the 'latest' tag."
echo ""
echo "Steps:"
echo "  1. Create admission control config at /etc/kubernetes/admission/admission-config.yaml:"
echo "     apiVersion: apiserver.config.k8s.io/v1"
echo "     kind: AdmissionConfiguration"
echo "     plugins:"
echo "     - name: ImagePolicyWebhook"
echo "       configuration:"
echo "         imagePolicy:"
echo "           kubeConfigFile: /etc/kubernetes/admission/kubeconfig.yaml"
echo "           allowTTL: 50"
echo "           denyTTL: 50"
echo "           retryBackoff: 500"
echo "           defaultAllow: false"
echo ""
echo "  2. Create kubeconfig for webhook at /etc/kubernetes/admission/kubeconfig.yaml"
echo "     pointing to the webhook service"
echo ""
echo "  3. Enable the admission plugin in kube-apiserver:"
echo "     --enable-admission-plugins=...,ImagePolicyWebhook"
echo "     --admission-control-config-file=/etc/kubernetes/admission/admission-config.yaml"
echo ""
echo "  4. Verify: kubectl run test --image=nginx:latest should be denied"
echo ""
echo "Note: Requires node access to modify apiserver manifest"
