#!/bin/bash
echo "[*] Setting up Q12 — Kubernetes Cluster Upgrade"
echo ""
echo "Task:"
echo "  Upgrade the cluster from 1.29.0 to 1.29.1"
echo ""
echo "Steps:"
echo "  Control Plane:"
echo "    1. apt-get update"
echo "    2. apt-cache madison kubeadm | grep 1.29.1"
echo "    3. apt-get install -y kubeadm=1.29.1-1.1"
echo "    4. kubeadm upgrade plan"
echo "    5. kubeadm upgrade apply v1.29.1"
echo "    6. apt-get install -y kubelet=1.29.1-1.1 kubectl=1.29.1-1.1"
echo "    7. systemctl daemon-reload && systemctl restart kubelet"
echo ""
echo "  Worker Node:"
echo "    1. kubectl drain <node> --ignore-daemonsets"
echo "    2. SSH to worker: apt-get install -y kubeadm=1.29.1-1.1"
echo "    3. kubeadm upgrade node"
echo "    4. apt-get install -y kubelet=1.29.1-1.1 kubectl=1.29.1-1.1"
echo "    5. systemctl daemon-reload && systemctl restart kubelet"
echo "    6. kubectl uncordon <node>"
echo ""
echo "Note: This requires direct node access via SSH"
